branches:
  only:
  - travisbuild
language: java
jdk:
- oraclejdk8
script:
- mvn clean install -Dmaven.test.skip=true
notifications:
  slack:
    secure: HJDa50xwNCit6h1YhAn27LzhwURWMidlNQ00k5GYOHHr/SpSc5KLQL0Tn9hG6P4WE5WA5Cw0z0JdfxMpSgCCt5lGJx6zbRYds2l43hEvOvpNPeSwJtwFxZZsQEt39MWJJertEHeWKfDPu5WEErEuTMcOfCLWThuKFJ5rBxCCUMOLWe2PmKto4ecaTPDkUYoxxIo0KpSfM3taBtidGpOea+cIFzmf3CGpr6wadZoznMglZWsHl4IB3XBxhNYeKX2gDTUdBrf2lUgcywCdyze65BQDq+p+I9oVcQr3YYL7TOtV+u72wunYKOYeFF9altC1Cmj66mjR/h1IlJC3ggmy1NBTN3ThjAhAHInYUHUA9wfu1fXxUkgcQGm9EJqWkAHjX+ReJDuxFdN3VePIckCgRn1M67I7zfDnWOnDlIRDLOdLU8mugWJjblbDcAg5Na791HnG15jXf0OzunWvtCO4g65brE02pa08qxhdWMVk0XsspUZKJVkJgHGdl0j8r9gT3Boz2e2lWYbr+YeX721q+t0maFlpLkXUzGaulr6wg5Z5TLdWGJ2oQ57clQ6LJBckQoEMgaiDy4Ab0WMBMva3kZbRPdFmHP+CmgOBL39wQatq374dw0NpwCyQ5ikByxdMUaKTJA4kuELhi75svqlHxqBucdyx4dWExpwTyUf88Ss=
###
