---
branches:
  only:
    - travisbuild

language: java

jdk:
  - oraclejdk8

script:
  ##########################
  ### BUILD WITH MAVEN
  ##########################
  - mvn clean install -Dmaven.test.skip=true
